config/routes.rb
Rails.application.routes.draw do
  resources :projects
  get 'stylish_portfolios/index'
  get 'stylish_portfolios/download'

   root 'stylish_portfolios#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :content, :picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/stylish_portfolios_controller.rb
class StylishPortfoliosController < ApplicationController
  layout "stylish_portfolio"

  def index
  end
   def download
    send_file Rails.root.join('private', 'GradCV.docx'), :type=>"application/doc", :x_sendfile=>true
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/stylish_portfolio.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taofiqiya Adelakun Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Anonymous+Pro' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'stylish_portfolio/manifest.css', media: 'all' %>
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  <%= javascript_include_tag 'stylish_portfolio/manifest.js' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.content %></td>
        <td><%= project.picture %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @project.content %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @project.picture %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Start</span> Bootstrap
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Download</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Grayscale</h1>
                        <p class="intro-text">A free, responsive, one page Bootstrap theme.<br>Created by Start Bootstrap.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Grayscale</h2>
                <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
                <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
                <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Download Grayscale</h2>
                    <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
                    <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact Start Bootstrap</h2>
                <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
                <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="js/jquery.easing.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom Theme JavaScript -->
    <script src="js/grayscale.js"></script>

</body>

</html>

app/views/stylish_portfolios/_about.html.erb
<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center ">
                <h2>About Me</h2>
                <hr class="small">
                <p class="lead">Hello, my name is Taofiqiya Adelakun I am a graduate of Applied Information Technology from Staffordshire university. I have just finished my Masters in Web an Cloud Computing. I love programming, learning new technology to enhance my skills is a passion of mine. I develop in the backend and front end.A new technology that I am learning is the MEAN Stack. Currently looking for a challenging role in software development that would allow me to use and improve on my skills as a Software Developer. If I am not writing code I could be found enjoying a movie or running.  </p>
            </div>
        </div>
    </div>
</section>

app/views/stylish_portfolios/_call_to_action.html.erb
<aside class="call-to-action bg-primary">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h3>The buttons below are impossible to resist.</h3>
                <a href="#" class="btn btn-lg btn-light">Click Me!</a>
                <a href="#" class="btn btn-lg btn-dark">Look at Me!</a>
            </div>
        </div>
    </div>
</aside>

app/views/stylish_portfolios/_callout.html.erb
<aside id="callout" class="callout">
    <div class="text-vertical-center">
      <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>Skills</h2>
                <hr class="small">
                <div class="row">
                    
                    <div class="col-md-6 col-sm-6">
                        <div class="service-item">
                           <h3> Server Side Programming language</h3>
                                           <hr class="small">
                            <h4>
                                Ruby, Ruby on Rails<br> PHP <br> Python, Django, Tkinter
                            </h4>
                            <h3> Client Side Programming language</h3>
                                            <hr class="small">
                            <h4>
                               HTML, CSS, SCSS Bootstrap <br> Javascript, Jquery
                            </h4>
                            <h3>OS</h3>
                            <h4>Windows , Linux, OSX</h4>
                          
                            
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        
                                                      <h3> Other Technologies</h3>
                                                                      <hr class="small">
                            <h4> Git version control</h4>
                             <h4> Heroku</h4>
                              <h4> Cloud9 cloud based IDE</h4>
                               <h3> Database</h3>
                                               <hr class="small">
                            <h4> <strong>SQL</strong> MySQL, SQLite, PostgreSQL</h4>
                              <h4> <strong>NoSQL</strong> MongodbL, Cassandra</h4>
                            
                            
                            
                        
                        </div>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        </div>
    </div>
</aside>

app/views/stylish_portfolios/_footer.html.erb
<footer id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h4><strong>TAOFIQIYA ADELAKUN</strong>
                </h4>
                <br>
                <ul class="list-inline">
                     
                    <li>
                        <a href="https://www.instagram.com/ayamgood" target="_blank"><i class="fa fa-instagram fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="https://twitter.com/ayamgood" target="_blank"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                    </li>
                    <li>
                        <a href="https://www.linkedin.com/in/taofiqiya-adelakun-a19b6a10a?trk=hp-identity-name" target="_blank"><i class="fa fa-linkedin fa-fw fa-3x"></i></a>
                    </li>
                </ul>
                <hr class="small">
                <p class="text-muted">Copyright &copy; TAOFIQIYA ADELAKUN 2016</p>
            </div>
        </div>
    </div>
</footer>

app/views/stylish_portfolios/_header.html.erb
<header id="top" class="header">
    <div class="text-vertical-center">
        <h1>Hello i am TAOFI</h1>
        <h3>I am a software developer, Welcome to my Portfolio </h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg">About Me</a>
        <a href="#portfolio" class="btn btn-lg btn-light">Portfolio</a>
    </div>
</header>

app/views/stylish_portfolios/_map.html.erb
<section id="contact" class="map">
    <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed"></iframe>
    <br />
    <small>
        <a href="https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;aq=0&amp;oq=twitter&amp;sll=28.659344,-81.187888&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Twitter,+Inc.,+Market+Street,+San+Francisco,+CA&amp;t=m&amp;z=15&amp;iwloc=A"></a>
    </small>
    </iframe>
</section>

app/views/stylish_portfolios/_navigation.html.erb
<a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
<nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>
        <li class="sidebar-brand">
            <a href="#top"  onclick = $("#menu-close").click(); >Menu</a>
        </li>
        <li>
            <a href="#top" onclick = $("#menu-close").click(); >Home</a>
        </li>
        <li>
            <a href="#about" onclick = $("#menu-close").click(); >About Me</a>
        </li>
                <li>
            <a href="#callout" onclick = $("#menu-close").click(); >Skills</a>
        </li>
        <li>
            <a href="#portfolio" onclick = $("#menu-close").click(); >Portfolio</a>
        </li>

        <li>
            <a href="#contact" onclick = $("#menu-close").click(); >Contact</a>
        </li>
    </ul>
</nav>

app/views/stylish_portfolios/_portfolio.html.erb
<section id="portfolio" class="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-lg-offset-1 text-center">
                <h2>My Portfolio</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-6">
                        <div class="portfolio-item">
                            <div class="panel panel-default">
                                 <div class="panel-heading">
                                     <h3 class="panel-title">Snow App - Social Media App for Sheffield Hallam University (MSc Project)</h3>
                                    </div>
                                    <div class="portfolio-item">
                            <a href="#">
                                <%= image_tag "stylish_portfolio/port1.PNG", class: "img-portfolio img-responsive" %>
                            </a>
                        </div>
              <div class="panel-body">
                <p align = "left">This Application was my final project for my MSc. The application is similar to twitter</p> 
       
                <h2>Ruby on Rails</h2>
                <h2>Bootstrap HTML, CSS, SCSS, JavaScript</h2>
                <h2>Rubygems </h2>
                <h2>Authorization and authentication built from scratch</h2>
                <h2>Unit Testing</h2>

                 </div>
              <div class="panel-footer">
                  <div class="btn btn-primary"><a href="https://bitbucket.org/ayomey/project/src" target="_blank">
                                <i class="fa fa-bitbucket"></i> Source Code</a></div>
                             <div class="btn btn-success"><a href="https://shusnowapp.herokuapp.com/" target="_blank">
                                <i class="fa fa-eye"></i> Preview</a></div>
               </div>
                </div>
                            
              </div>
                       
             </div>
             
             <div class="col-md-6">
                        <div class="portfolio-item">
                            <div class="panel panel-default">
                                 <div class="panel-heading">
                                     <h3 class="panel-title">SHUBook Store - Ecommerce App (Group Work)</h3>
                                    </div>
                                    <div class="portfolio-item">
                            <a href="#">
                                <%= image_tag "stylish_portfolio/port2.PNG", class: "img-portfolio img-responsive" %>
                            </a>
                        </div>
              <div class="panel-body">
                  
               <p align = "left"> For a group assignment for a database and web module during my Masters this app was produced.The app allow anyone to sell or
                buy books</p>
                <h2>PHP</h2><h2>MySql</h2><h2>Bootstrap HTML, CSS, JavaScript, Jquery</h2>
                <h3 align = "left">Group mates</h3>
                  <p align = "left">CHRISTOPHER IKHONMIOTOR </p>
                  <p align = "left">Intisar Omar</p>
                 </div>
              <div class="panel-footer">
                  <div class="btn btn-primary"><a href="https://bitbucket.org/ayomey/shubook/src" target="_blank">
                                <i class="fa fa-bitbucket"></i> Source Code</a></div>
                             <div class="btn btn-success"><a href="https://frozen-garden-92687.herokuapp.com" target="_blank">
                                <i class="fa fa-eye"></i> Preview</a></div>
               </div>
                </div>
                            
              </div>
                       
             </div>
             <div class="col-md-6">
                        <div class="portfolio-item">
                            <div class="panel panel-default">
                                 <div class="panel-heading">
                                     <h3 class="panel-title">SCITEC4SEN A non profit organisation </h3>
                                    </div>
                                    <div class="portfolio-item">
                            <a href="#">
                                <%= image_tag "stylish_portfolio/port3.PNG", class: "img-portfolio img-responsive" %>
                            </a>
                        </div>
              <div class="panel-body">
                <p align = "left">
                   The organisation is working to provide science education to visually impired students in Nigeria.
                   I started volunteering for them in January 2016. The web app allow visitors to
                   learn about the organisation and thier programmes and also users can register for their
                   forthcoming confrence and submit abstract
                </p>

                <h2>Ruby on Rails</h2>
                <h2>Bootstrap, HTML, CSS, SCSS  </h2>
                <h2>devise gem for authorization and authentication</h2>
                
                 </div>
              <div class="panel-footer">
                             <div class="btn btn-success"><a href="http://www.scitec4sen.com/" target="_blank">
                                <i class="fa fa-eye"></i> Preview</a></div>
               </div>
                </div>
                            
              </div>
                       
             </div>
             

                   
                </div>
                <!-- /.row (nested) -->
                <a href="#top" class="btn btn-dark">Back To Top</a>
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

app/views/stylish_portfolios/_services.html.erb
<!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
<section id="services" class="services bg-primary">
    <div class="container">
        <div class="row text-center">
            <div class="col-lg-10 col-lg-offset-1">
                <h2>Skills</h2>
                <hr class="small">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-cloud fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-compass fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-flask fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="service-item">
                            <span class="fa-stack fa-4x">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-shield fa-stack-1x text-primary"></i>
                        </span>
                            <h4>
                                <strong>Service Name</strong>
                            </h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <a href="#" class="btn btn-light">Learn More</a>
                        </div>
                    </div>
                </div>
                <!-- /.row (nested) -->
            </div>
            <!-- /.col-lg-10 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>

app/views/stylish_portfolios/index.html.erb
<%= render "navigation" %>
<%= render "header" %>
<%= render "about" %>
<%= render "callout" %>
<%= render "portfolio" %>
<%= render "footer" %>